version: 2.1
orbs:   
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run:
          name: listing the files and folders
          command: ls -lrth && pwd
      - aws-s3/sync:
          from: .
          to: "s3://static-website-circleci"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
            overwrite: true
      - run:
          name: installing awscli
          command: pip install --upgrade awscli
      # - run:
      #     name: Deploying to S3
      #     command: aws s3 sync . s3://static-website-circleci
      - run:
          name: waiting for 100 sec
          command: sleep 100
      - run:
          name: Following files will be deleted
          command: aws s3 rm s3://static-website-circleci/ --dryrun --recursive --include "*"
      - run:
          name: Undeploying the application
          command: aws s3 rm s3://static-website-circleci/ --recursive --include "*"

          
workflows:
  s3-example:
    jobs:
      - build:
          context: aws-s3