version: 2.1
jobs:
  deploy:
    working_directory: ~/static-website
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys: 
            - my-cache-v1
      - run:
          name: listing the files and folders
          command: ls -lrth && pwd && ls -lrth /usr/local/bin
      - run:
          name: installing awscli
          command: pip install --upgrade pip && pip install --upgrade awscli
      - save_cache:
          key: my-cache-v1
          paths:
            - "/usr/local/bin"
      - run:
          name: Deploying to S3
          command: aws s3 sync ~/static-website s3://static-website-circleci
  undeploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys: 
            - my-cache-v1
      - run:
          name: Following files will be deleted
          command: aws s3 rm s3://static-website-circleci/ --dryrun --recursive --include "*"
      - run:
          name: Undeploying the application
          command: aws s3 rm s3://static-website-circleci/ --recursive --include "*"         
workflows:
  s3-example:
    jobs:
      - deploy:
          context: aws-s3
      - approve-to-undeploy:
          type: approval
          requires:
            - deploy
      - undeploy:
          context: aws-s3
          requires:
            - approve-to-undeploy