version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run:
          name: listing the files and folders
          command: ls -lrth
      - run:
          name: Upload file to S3
          command: aws s3 sync . s3://static-website-circleci/ --delete
workflows:
  s3-example:
    jobs:
      - build:
          context: aws-s3