version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run:
          name: creating a directory and copying the files to it
          command: |
            mkdir -p bucket
            cp . bucket
      - aws-s3/sync:
          from: bucket
          to: 's3://static-website-circleci/*'
workflows:
  s3-example:
    jobs:
      - build:
          context: aws-s3